apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-app-service
  labels:
    app: myapp
  {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.appService.type }}
  selector:
    app: myapp
  {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.appService.ports | toYaml | nindent 2 -}}