apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "operator.fullname" . }}-pvc-lim
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: cust1-mypool-lim