name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Fmt
      run: go fmt ./...
      
    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test  -coverprofile c.out ./...
  
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        # The report file must be there, otherwise Code Climate won't find it
        coverageCommand: go test  -coverprofile c.out ./...
        coverageLocations: ${{github.workspace}}/c.out:gocov

#     - name: Create kind cluster
#       uses: helm/kind-action@v1.0.0-alpha.3
#       with:
#         install_local_path_provisioner: true
        
#     - name: cert install
#       run: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.1/cert-manager.yaml 
        
#     - name: helm install
#       run: helm install my-release ./mychart -n my-namespace --create-namespace  

      

