name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Fmt
      run: go fmt ./...
      
#     - name: Vet
#       run: go vet ./...
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run
      run: cat test_data/kustomize.output | go run cmd/helmify/main.go -v mychart
      
    - name: Helm lint
      uses: azure/setup-helm@v1
      with:
        version: 'v3.6.2'
     
    - name: helm
      run: helm lint mychart --strict 
      
#     - name: Run chart-testing (lint)
#       id: lint
#       uses: HexF/chart-testing-action@v3.0.0
#       with:
#         command: lint --chart-dirs mychart --charts mychart

#     - name: Create kind cluster
#       uses: helm/kind-action@v1.0.0-alpha.3
#       with:
#         install_local_path_provisioner: true
#       # Only build a kind cluster if there are chart changes to test.
#       if: steps.lint.outputs.changed == 'true'

#     - name: Run chart-testing (install)
#       uses: HexF/chart-testing-action@v3.0.0
#       with:
#         command: install --chart-dirs mychart --charts mychart
      
#    - name: helm-check
#      uses: igabaydulin/helm-check-action@0.1.4
#       env:
#         CHART_LOCATION: ./mychart
#         CHART_VALUES: ./hmychart/values.yaml
         
#    - name: Validate Helm
#     uses: WyriHaximus/github-action-helm3@v2.0
#     with:
#         exec: helm lint ./mychart/  --strict 
      

